name: CI
on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache-dependency-path: ./go.sum
      - name: build
        run: |
          go build ./cmd/crawler/crawl.go

  test:
    runs-on: ubuntu-latest
    steps:
      - name: check-out
        uses: actions/checkout@v4
      - name: setup go
        uses: actions/setup-go@v4
        with:
          go-version: 1.21.5
          cache-dependency-path: ./go.sum
      - name: test
        run: |
          go test ./... -v